global:
  - LD_LIBRARY_PATH=/usr/local/lib
before_install:
  - yes | sudo add-apt-repository ppa:cmrx64/cargo
  - sudo apt-get update
install:
  - sudo apt-get install cargo
  - curl http://static.rust-lang.org/rustup.sh | sudo sh -
script:
  - rustc --version
  - cargo build
